### ISSUE TITLE
how can we get this in the EM repo

### ISSUE THREAD

**Issue by cgicgi** [w-flo/eu-emission-factors#2]
Dear @w-flo ,

thanks a lot for your great work. Unfortunately it has not been integrated so far. I'd like to discuss with you how we can get these well-calculated emission factors to a broader audience and if possible inside the EM repo.
Would you be interested in such a discussion?

Best
Siggi

**Comment by cgicgi** [comment]
Update:
https://github.com/electricitymaps/electricitymaps-contrib/pull/6308

**Comment by w-flo** [comment]
Hi @cgicgi ! Thanks for your feedback :-)

I'm not sure if there is anything I can do to help with EM integration. I would definitely support EM using as much as they want from this repo (that is, EM and anyone else is free to copy my work from this repo, partially or completely).

Note: I'm not 100% convinced the "heat allocation" stuff for combined heat and power plants that I came up with is the right thing to do. I do suspect it's better than what I think EM does, but maybe there is simply no reliable way to estimate heat generation of a CHP plant for a given year, as the "free heat allocation" ETS emission allowances are based on the heat provided a few years ago (I don't remember the details right now, but that's how I understood the ETS docs). My method based on degree days is definitely not very reliable, as CHP plant utilization probably depends on many more things than just how cold it is outside. Maybe there is some other data source with more details for CHP plants that I've missed, it would be very useful.

So maybe one step forward could be: EM keeps its current method for emission factor estimation, but they include the [manual mapping of ENTSO-E data to ETS data in my repo](https://github.com/w-flo/eu-emission-factors/blob/main/data/2022/manual_matches.csv). I'd gladly provide the list in a different format if that helps. That way, the "sample size" of power plants for each country to estimate emission factors would probably increase considerably, which might help. It wouldn't solve the CHP issue, but I'm not too happy with the solution in my repo anyway.

**Comment by VIKTORVAV99** [comment]
Thank you for all your work here @w-flo, I and @mathilde-daugy have already talked about integrating the manual plant mapping and will try and do so as soon as possible but we do have some other commitments at the moment.

I think the CSV file is perfectly fine, if it needs to be reformatted we'll take care of it. 😊

Thanks once again!
And thank you @cgicgi for reminding us!

**Comment by w-flo** [comment]
Oh, thank you for updating us on the current status! Sounds great.

If there is anything I could do programatically in my rust code (like creating a CSV that has EICs instead of power plant names, or some different ETS identifier schema, or filtering the file based on my emission factor estimation results, or anything like that) to help you guys later on, feel free to let me know.

**Comment by cgicgi** [comment]
Thank you @VIKTORVAV99 and mathilde for being open to these suggestions!
Thanks @w-flo not only for the work you did here but also for being open about the flaws of the used methodology.

Actually, I must admit, I am a bit disappointed that there is no official EU institution that takes care for these questions. Reducing CO2-emissions is the main challenge nowadays and we do not even know exactly where they occur. The necessity to map the ENTSO-E to the ETS data manually (!) is ... well, I have no words.

Neverthelesse, I'll happily close this issue.
